Add cron task to download new plugins
redcraft-org/redcraft_plugins_updater pull request #6
Opened 2020-11-30 03:51 UTC by lululombard

This adds a Cron task to download new plugins.

It will run every day a 3 a.m. on GitHub actions.

It been tested and it works! https://github.com/redcraft-org/redcraft_plugins_updater/actions/runs/390809798

2020-11-30 15:00 UTC, Likyaz submitted a review, later dismissed

2020-11-30 18:23 UTC, Omeganx requested changes
change name to 'Download' instead of 'Test project'.

2020-11-30 21:31 UTC, lululombard commented on .github/workflows/run.yml
> +name: Test project
```suggestion
name: Download plugins
```

2020-11-30 21:34 UTC, Omeganx approved these changes

2020-11-30 21:38 UTC, Omeganx approved these changes

2020-12-01 01:31 UTC, Nano112 reviewed
tu pourrais faire mieux 4/20

2020-12-01 01:31 UTC, Nano112 approved these changes

2020-12-01 01:31 UTC, merged